apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: bottlerocket
spec:
  labels:
    os: bottlerocket
    image: cached
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.large", "m5.2xlarge"]
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: bottlerocket
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: bottlerocket
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: optional
  securityGroupSelector:
    alpha.eksctl.io/cluster-name: test-cluster
    aws:cloudformation:logical-id: ClusterSharedNodeSecurityGroup
  subnetSelector:
    alpha.eksctl.io/cluster-name: test-cluster
    kubernetes.io/role/internal-elb: "1"
  tags:
    KarpenerProvisionerName: bottlerocket
  amiFamily: Bottlerocket
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 10Gi
        volumeType: gp3
        deleteOnTermination: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 80Gi
        volumeType: gp3
        snapshotID: snap-02349d69820e10135
        iops: 4000
        deleteOnTermination: true
        throughput: 1000
